// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadAocd1p2 returns the embedded CollectionSpec for aocd1p2.
func loadAocd1p2() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Aocd1p2Bytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load aocd1p2: %w", err)
	}

	return spec, err
}

// loadAocd1p2Objects loads aocd1p2 and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*aocd1p2Objects
//	*aocd1p2Programs
//	*aocd1p2Maps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAocd1p2Objects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAocd1p2()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// aocd1p2Specs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd1p2Specs struct {
	aocd1p2ProgramSpecs
	aocd1p2MapSpecs
	aocd1p2VariableSpecs
}

// aocd1p2ProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd1p2ProgramSpecs struct {
	TraceEchoEntry *ebpf.ProgramSpec `ebpf:"trace_echo_entry"`
}

// aocd1p2MapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd1p2MapSpecs struct {
	State *ebpf.MapSpec `ebpf:"state"`
}

// aocd1p2VariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd1p2VariableSpecs struct {
}

// aocd1p2Objects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAocd1p2Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd1p2Objects struct {
	aocd1p2Programs
	aocd1p2Maps
	aocd1p2Variables
}

func (o *aocd1p2Objects) Close() error {
	return _Aocd1p2Close(
		&o.aocd1p2Programs,
		&o.aocd1p2Maps,
	)
}

// aocd1p2Maps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAocd1p2Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd1p2Maps struct {
	State *ebpf.Map `ebpf:"state"`
}

func (m *aocd1p2Maps) Close() error {
	return _Aocd1p2Close(
		m.State,
	)
}

// aocd1p2Variables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAocd1p2Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd1p2Variables struct {
}

// aocd1p2Programs contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAocd1p2Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd1p2Programs struct {
	TraceEchoEntry *ebpf.Program `ebpf:"trace_echo_entry"`
}

func (p *aocd1p2Programs) Close() error {
	return _Aocd1p2Close(
		p.TraceEchoEntry,
	)
}

func _Aocd1p2Close(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed aocd1p2_bpfeb.o
var _Aocd1p2Bytes []byte
