// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type aocd3InputWorkspace struct {
	_          structs.HostLayout
	Locked     uint32
	Input      [500]uint32
	InputLen   uint32
	NextK      int32
	_          [4]byte
	BestSuffix [13]int64
}

// loadAocd3 returns the embedded CollectionSpec for aocd3.
func loadAocd3() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Aocd3Bytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load aocd3: %w", err)
	}

	return spec, err
}

// loadAocd3Objects loads aocd3 and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*aocd3Objects
//	*aocd3Programs
//	*aocd3Maps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAocd3Objects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAocd3()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// aocd3Specs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd3Specs struct {
	aocd3ProgramSpecs
	aocd3MapSpecs
	aocd3VariableSpecs
}

// aocd3ProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd3ProgramSpecs struct {
	EpollWork *ebpf.ProgramSpec `ebpf:"epoll_work"`
}

// aocd3MapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd3MapSpecs struct {
	InputWorkspaces *ebpf.MapSpec `ebpf:"input_workspaces"`
}

// aocd3VariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd3VariableSpecs struct {
	FirstUnworkableInputIndex *ebpf.VariableSpec `ebpf:"first_unworkable_input_index"`
	FirstWorkableInputIndex   *ebpf.VariableSpec `ebpf:"first_workable_input_index"`
}

// aocd3Objects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAocd3Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd3Objects struct {
	aocd3Programs
	aocd3Maps
	aocd3Variables
}

func (o *aocd3Objects) Close() error {
	return _Aocd3Close(
		&o.aocd3Programs,
		&o.aocd3Maps,
	)
}

// aocd3Maps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAocd3Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd3Maps struct {
	InputWorkspaces *ebpf.Map `ebpf:"input_workspaces"`
}

func (m *aocd3Maps) Close() error {
	return _Aocd3Close(
		m.InputWorkspaces,
	)
}

// aocd3Variables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAocd3Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd3Variables struct {
	FirstUnworkableInputIndex *ebpf.Variable `ebpf:"first_unworkable_input_index"`
	FirstWorkableInputIndex   *ebpf.Variable `ebpf:"first_workable_input_index"`
}

// aocd3Programs contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAocd3Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd3Programs struct {
	EpollWork *ebpf.Program `ebpf:"epoll_work"`
}

func (p *aocd3Programs) Close() error {
	return _Aocd3Close(
		p.EpollWork,
	)
}

func _Aocd3Close(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed aocd3_bpfel.o
var _Aocd3Bytes []byte
