// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadAocd2p1 returns the embedded CollectionSpec for aocd2p1.
func loadAocd2p1() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Aocd2p1Bytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load aocd2p1: %w", err)
	}

	return spec, err
}

// loadAocd2p1Objects loads aocd2p1 and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*aocd2p1Objects
//	*aocd2p1Programs
//	*aocd2p1Maps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAocd2p1Objects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAocd2p1()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// aocd2p1Specs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd2p1Specs struct {
	aocd2p1ProgramSpecs
	aocd2p1MapSpecs
	aocd2p1VariableSpecs
}

// aocd2p1ProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd2p1ProgramSpecs struct {
	HandleEgress *ebpf.ProgramSpec `ebpf:"handle_egress"`
}

// aocd2p1MapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd2p1MapSpecs struct {
	State *ebpf.MapSpec `ebpf:"state"`
}

// aocd2p1VariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd2p1VariableSpecs struct {
}

// aocd2p1Objects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAocd2p1Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd2p1Objects struct {
	aocd2p1Programs
	aocd2p1Maps
	aocd2p1Variables
}

func (o *aocd2p1Objects) Close() error {
	return _Aocd2p1Close(
		&o.aocd2p1Programs,
		&o.aocd2p1Maps,
	)
}

// aocd2p1Maps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAocd2p1Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd2p1Maps struct {
	State *ebpf.Map `ebpf:"state"`
}

func (m *aocd2p1Maps) Close() error {
	return _Aocd2p1Close(
		m.State,
	)
}

// aocd2p1Variables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAocd2p1Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd2p1Variables struct {
}

// aocd2p1Programs contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAocd2p1Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd2p1Programs struct {
	HandleEgress *ebpf.Program `ebpf:"handle_egress"`
}

func (p *aocd2p1Programs) Close() error {
	return _Aocd2p1Close(
		p.HandleEgress,
	)
}

func _Aocd2p1Close(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed aocd2p1_bpfeb.o
var _Aocd2p1Bytes []byte
