// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadAocd2p2 returns the embedded CollectionSpec for aocd2p2.
func loadAocd2p2() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Aocd2p2Bytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load aocd2p2: %w", err)
	}

	return spec, err
}

// loadAocd2p2Objects loads aocd2p2 and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*aocd2p2Objects
//	*aocd2p2Programs
//	*aocd2p2Maps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAocd2p2Objects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAocd2p2()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// aocd2p2Specs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd2p2Specs struct {
	aocd2p2ProgramSpecs
	aocd2p2MapSpecs
	aocd2p2VariableSpecs
}

// aocd2p2ProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd2p2ProgramSpecs struct {
	HandleEgress *ebpf.ProgramSpec `ebpf:"handle_egress"`
}

// aocd2p2MapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd2p2MapSpecs struct {
	State *ebpf.MapSpec `ebpf:"state"`
}

// aocd2p2VariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd2p2VariableSpecs struct {
}

// aocd2p2Objects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAocd2p2Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd2p2Objects struct {
	aocd2p2Programs
	aocd2p2Maps
	aocd2p2Variables
}

func (o *aocd2p2Objects) Close() error {
	return _Aocd2p2Close(
		&o.aocd2p2Programs,
		&o.aocd2p2Maps,
	)
}

// aocd2p2Maps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAocd2p2Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd2p2Maps struct {
	State *ebpf.Map `ebpf:"state"`
}

func (m *aocd2p2Maps) Close() error {
	return _Aocd2p2Close(
		m.State,
	)
}

// aocd2p2Variables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAocd2p2Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd2p2Variables struct {
}

// aocd2p2Programs contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAocd2p2Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd2p2Programs struct {
	HandleEgress *ebpf.Program `ebpf:"handle_egress"`
}

func (p *aocd2p2Programs) Close() error {
	return _Aocd2p2Close(
		p.HandleEgress,
	)
}

func _Aocd2p2Close(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed aocd2p2_bpfel.o
var _Aocd2p2Bytes []byte
