// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadAocd1p1 returns the embedded CollectionSpec for aocd1p1.
func loadAocd1p1() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Aocd1p1Bytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load aocd1p1: %w", err)
	}

	return spec, err
}

// loadAocd1p1Objects loads aocd1p1 and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*aocd1p1Objects
//	*aocd1p1Programs
//	*aocd1p1Maps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAocd1p1Objects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAocd1p1()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// aocd1p1Specs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd1p1Specs struct {
	aocd1p1ProgramSpecs
	aocd1p1MapSpecs
	aocd1p1VariableSpecs
}

// aocd1p1ProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd1p1ProgramSpecs struct {
	TraceEchoEntry *ebpf.ProgramSpec `ebpf:"trace_echo_entry"`
}

// aocd1p1MapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd1p1MapSpecs struct {
	State *ebpf.MapSpec `ebpf:"state"`
}

// aocd1p1VariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type aocd1p1VariableSpecs struct {
}

// aocd1p1Objects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAocd1p1Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd1p1Objects struct {
	aocd1p1Programs
	aocd1p1Maps
	aocd1p1Variables
}

func (o *aocd1p1Objects) Close() error {
	return _Aocd1p1Close(
		&o.aocd1p1Programs,
		&o.aocd1p1Maps,
	)
}

// aocd1p1Maps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAocd1p1Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd1p1Maps struct {
	State *ebpf.Map `ebpf:"state"`
}

func (m *aocd1p1Maps) Close() error {
	return _Aocd1p1Close(
		m.State,
	)
}

// aocd1p1Variables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAocd1p1Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd1p1Variables struct {
}

// aocd1p1Programs contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAocd1p1Objects or ebpf.CollectionSpec.LoadAndAssign.
type aocd1p1Programs struct {
	TraceEchoEntry *ebpf.Program `ebpf:"trace_echo_entry"`
}

func (p *aocd1p1Programs) Close() error {
	return _Aocd1p1Close(
		p.TraceEchoEntry,
	)
}

func _Aocd1p1Close(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed aocd1p1_bpfel.o
var _Aocd1p1Bytes []byte
